"""Generate evidence-backed technical metrics and role-specific resume candidates.

Missing experiments remain unmeasured. No aspirational numbers or economic
projections enter accomplishment claims. Run from the repository root.
"""

import hashlib
import json
import xml.etree.ElementTree as ET
from pathlib import Path


def read(path):
    return json.loads(Path(path).read_text(encoding="utf-8"))


def link(path):
    return f"[{Path(path).name}](../{path})"


def generate():
    sources = {}

    def evidence(path):
        sources[path] = hashlib.sha256(Path(path).read_bytes()).hexdigest()
        return read(path)

    city = evidence("artifacts/cities/source-health.json")
    networks = evidence("artifacts/cities/networks.json")
    study = evidence("artifacts/cities/study-summary.json")
    detection = evidence("artifacts/benchmarks/real_detection.json")
    tracking = evidence("artifacts/benchmarks/real_tracking.json")
    pipeline = evidence("artifacts/benchmarks/real_video_pipeline.json")
    forecast = evidence("artifacts/benchmarks/real_forecasting.json")
    performance = evidence("artifacts/cities/performance.json")
    context = evidence("artifacts/cities/toronto-intelligence.json")
    counts = evidence("artifacts/cities/toronto-counts.json")
    neural = evidence("artifacts/cities/graph-forecast.json")
    vision = evidence("artifacts/cities/vision-v3.json")
    flow = evidence("artifacts/cities/visual-flow.json")
    traffic = evidence("artifacts/cities/traffic-context.json")
    robustness = evidence("artifacts/cities/perception-robustness.json")
    runtime = evidence("artifacts/cities/forecast-runtime-profile.json")
    operational = [c for c in city["cities"] if c["status"] == "metadata_available"]
    catalogs = sum(len(c["cameras"]) for c in operational)
    observations = {
        (c["city"], o["camera_id"], o["id"])
        for c in city["cities"]
        for o in c["observations"]
        if "counts" in o
    }
    observations.add(
        (context["city"], context["observation"]["camera_id"], context["observation"]["id"])
    )
    smoke = evidence("artifacts/cities/city-intelligence-smoke.json")
    for record in smoke["records"]:
        for attempt in record["attempts"]:
            if "context" in attempt:
                observation = attempt["context"]["observation"]
                observations.add((record["city"], observation["camera_id"], observation["id"]))
    cameras = {(c, o) for c, o, _ in observations}
    road_count = sum(len(n["roads"]) for n in networks["networks"])
    controlled = 0
    for n in networks["networks"]:
        import gzip

        tree = ET.fromstring(
            gzip.decompress(
                Path(f"artifacts/cities/scenarios/{n['city']}/network.net.xml.gz").read_bytes()
            )
        )
        for logic in tree.findall("tlLogic"):
            green = [
                p
                for p in logic.findall("phase")
                if any(c in "Gg" for c in p.attrib["state"])
                and all(c in "rGgs" for c in p.attrib["state"])
            ]
            controlled += len(green) >= 2
    hardware = pipeline["hardware"]["cpu"]
    metric_lines = [
        "# Verified engineering metrics",
        "",
        "Generated by `python scripts/generate_engineering_metrics.py` from existing evidence. Re-running does not execute benchmarks. Historical and new experiments remain separate.",
        "",
        "| Category | Actual measurement | Evidence / qualification |",
        "|---|---|---|",
        f"| Official ingestion | {len(operational)} city catalogs; {catalogs:,} discovered cameras; {len(cameras)} sampled cameras; {len(observations)} processed snapshot observations | {link('artifacts/cities/source-health.json')}, {link('artifacts/cities/toronto-intelligence.json')}, {link('artifacts/cities/city-intelligence-smoke.json')}; catalog discovery does not verify every image. |",
        f"| Connected multi-city smoke | {sum(a.get('state') == 'complete' for r in smoke['records'] for a in r['attempts'])} actual 120-second matched simulation pairs; {sum(a.get('state') == 'zero_motor_observation_not_simulated' for r in smoke['records'] for a in r['attempts'])} zero-motor observations refused for demand conversion | {link('artifacts/cities/city-intelligence-smoke.json')}; one-time checks, generated OD and unvalidated residence assumptions, not held-out performance or field savings. |",
        f"| Official counts | {len(counts['records'])} fifteen-minute bins; {counts['study']['total_vehicle']:,} motor vehicles | {link('artifacts/cities/toronto-counts.json')}; one intersection on {counts['study']['latest_count_date']}; historical, not current demand or unique vehicle identities. |",
        f"| Network scope | {road_count} road segments; {controlled} multi-phase modeled controlled intersections across {len(networks['networks'])} corridors | {link('artifacts/cities/networks.json')}; real OSM geometry, generated signal plans, uncalibrated demand. |",
        f"| Historical detection | mAP@50 {detection['metrics']['map50']:.6f}; mAP@50:95 {detection['metrics']['map50_95']:.6f} | {link('artifacts/benchmarks/real_detection.json')}; vehicle aggregate class; three UA-DETRAC test sequences. |",
        f"| Historical tracking | IDF1 {tracking['metrics']['IDF1']:.6f}; HOTA {tracking['metrics']['HOTA']:.6f}; {tracking['metrics']['IDSW']:.0f} identity switches | {link('artifacts/benchmarks/real_tracking.json')}; continuous annotated UA-DETRAC sequences; not city snapshots. |",
        f"| Historical complete CV pipeline | {pipeline['metrics']['pipeline_fps']:.3f} CPU FPS / {pipeline['metrics']['frames']:,} frames; peak RSS {pipeline['metrics']['memory_peak_rss_mb']:.1f} MiB | {link('artifacts/benchmarks/real_video_pipeline.json')}; {hardware}, CPU-only; includes analytics/persistence, lossless pre-encoding outside timing. |",
        f"| Candidate perception | YOLO26n mAP@50 {vision['candidate']['detection']['map50']:.6f}; IDF1 {vision['candidate']['tracking']['IDF1']:.6f}; {vision['candidate']['tracking']['IDSW']:.0f} vs {vision['original']['tracking']['IDSW']:.0f} identity switches | {link('artifacts/cities/vision-v3.json')}; slight mAP/recall/IDF1/HOTA regression; original YOLO11n retained. |",
        f"| Candidate detector/tracker stage | {vision['candidate']['stage_performance']['detector_tracker_fps']:.3f} vs {vision['original']['stage_performance']['detector_tracker_fps']:.3f} CPU FPS | {link('artifacts/cities/vision-v3.json')}; separate host runs, stage only; not complete-pipeline or isolated repeated speedup. |",
        f"| Continuous visual flow | {len(flow['rows'])} predeclared gate/direction/camera cases; {sum(r['observed_crossings'] for r in flow['rows'])} annotated crossing events; weighted count MAE {sum(r['count_mae_per_bin'] * r['bins'] for r in flow['rows']) / sum(r['bins'] for r in flow['rows']):.6f} / 2.4-second bin | {link('artifacts/cities/visual-flow.json')}; empty bins included, events are not unique vehicles; no physical queue or turning-movement accuracy claim. |",
        f"| Supplementary official context | {sum(c['status'] == 'available' for c in traffic['cities'])} road-event feeds; {sum(len(c['events']) for c in traffic['cities'])} reported listings; {sum(w['status'] == 'available' for w in traffic['weather'])} airport weather observations | {link('artifacts/cities/traffic-context.json')}; one-time check, scheduled listings not necessarily active closures; {traffic['cities'][0].get('malformed_records_omitted', 0)} malformed Toronto CSV rows omitted; no validated forecasting fusion. |",
        f"| Controlled CV sensitivity | {len(robustness['results'])} declared conditions × {robustness['results'][0]['frames']} actual held-out camera-prefix frames | {link('artifacts/cities/perception-robustness.json')}; synthetic brightness/blur/resize/JPEG degradations, not natural-weather validation. |",
        f"| Native classical forecast service | Warm p95 {runtime['warm_ms_p95']:.3f} ms; cold {runtime['cold_ms']:.1f} ms | {link('artifacts/cities/forecast-runtime-profile.json')}; 100 same-input warm calls, 207 predictions, checksum/features/cache included; HTTP/frontend excluded. |",
    ]
    old = forecast["metrics"]["horizons"]["5"]
    skill = 100 * (1 - old["atlas_gradient_boosting"]["mae"] / old["persistence"]["mae"])
    metric_lines.append(
        f"| Historical forecasting | {old['atlas_gradient_boosting']['mae']:.6f} mph MAE vs {old['persistence']['mae']:.6f} persistence; {skill:.2f}% reduction | {link('artifacts/benchmarks/real_forecasting.json')}; 207 METR-LA sensors; chronological 70/10/20; {old['persistence']['valid_targets']:,} valid five-minute targets. |"
    )
    new_path = Path("artifacts/cities/forecast-v3.json")
    new = None
    if new_path.exists():
        new = evidence(str(new_path).replace("\\", "/"))
        for h in new["results"]:
            selected = next(m for m in h["models"] if m["selected_on_validation"])
            baseline = (
                forecast["metrics"]["horizons"]
                .get(str(h["horizon_minutes"]), {})
                .get("atlas_gradient_boosting")
            )
            qualification = "Original baseline not measured for this horizon."
            if baseline:
                if baseline["valid_targets"] != selected["metrics"]["valid_targets"]:
                    raise ValueError("Original and new forecast target masks differ")
                improvement = 100 * (1 - selected["metrics"]["mae"] / baseline["mae"])
                qualification = (
                    f"Original {baseline['mae']:.6f} mph; {improvement:.2f}% relative reduction."
                )
            metric_lines.append(
                f"| Forecast v3 / {h['horizon_minutes']} min | {h['selected']}: {selected['metrics']['mae']:.6f} mph MAE; all-207-sensor p95 {selected['all_207_sensor_latency_ms_p95']:.3f} ms; model {selected['model_bytes']:,} bytes | {link('artifacts/cities/forecast-v3.json')}; validation-selected feature set. {qualification} Same historical test period, independent external replication pending; graph-assisted boosting, not a GNN. |"
            )
        for paired in new.get("paired_original_analysis", []):
            ci = paired["paired_day_block_reduction_ci95_pct"]
            metric_lines.append(
                f"| Classical forecast uncertainty / {paired['horizon_minutes']} min | 95% paired day-block MAE reduction interval [{ci[0]:.2f}, {ci[1]:.2f}]% vs original | {link('artifacts/cities/forecast-v3.json')}; 20,000 resamples, 24 test calendar days, residual temporal dependence remains. |"
            )
    for h in neural["results"]:
        m = next(m for m in h["models"] if m["model"] == h["selected_on_validation"])
        metric_lines.append(
            f"| Learned graph forecast / {h['horizon_minutes']} min | {m['metrics']['mae']:.6f} mph MAE; RMSE {m['metrics']['rmse']:.6f}; {m['parameters']:,} learned parameters; forward p95 {m['all_207_sensor_forward_ms_p95']:.3f} ms; checkpoint {m['checkpoint_bytes']:,} bytes | {link('artifacts/cities/graph-forecast.json')}; actual directional GNN, fixed training configuration, best epoch on validation, four CPU threads. Forward-only latency; 4096 sampled train origins, more targets than classical 200k-row budget. |"
        )
    for p in neural["paired_analysis"]:
        ci = p["paired_day_block_ci95_pct"]
        metric_lines.append(
            f"| Neural paired improvement / {p['horizon_minutes']} min | {p['reduction_pct']:.2f}% MAE reduction vs {p['baseline']}; paired day-block 95% interval [{ci[0]:.2f}, {ci[1]:.2f}]% | {link('artifacts/cities/graph-forecast.json')}; shared historical holdout; external and cross-network replication pending. |"
        )
    for suite in study["suites"]:
        for p in suite["paired"]:
            ci = p["paired_percent_ci95"]
            metric_lines.append(
                f"| Signal / {p['city']} | {p['mean_paired_reduction_pct']:.2f}% mean paired delay reduction vs {p['baseline']}; 95% bootstrap CI [{ci[0]:.2f}, {ci[1]:.2f}]; {p['wins']}/{p['pairs']} positive differences | {link('artifacts/cities/study-summary.json')}; {suite['scope']}; negative reductions are regressions. |"
            )
    total_runs = sum(s["runs"] for s in study["suites"])
    violations = sum(
        round(s["mean_metrics"]["modeled_safety_violations"] * s["seeds"])
        for suite in study["suites"]
        for s in suite["summaries"]
    )
    metric_lines.append(
        f"| Frozen nominal evaluation | {total_runs} completed runs; {violations} recorded modeled invariant violations | {link('docs/atlas-2-protocol.json')}; two predeclared twenty-seed cohorts, Linux SUMO 1.27.1. This verifies modeled constraints, not physical signal certification. |"
    )
    for r in performance["results"]:
        metric_lines.append(
            f"| Controller profile / {r['controller']} | p50 {r['latency_ms_p50']:.3f} ms; p95 {r['latency_ms_p95']:.3f} ms; RSS p95 {r['process_rss_mib_p95']:.2f} MiB | {link('artifacts/cities/performance.json')}; {r['samples']} matched synthetic eight-movement decisions, native CPU; prototype slower. |"
        )
    junit = Path("data/atlas-v3-pytest.xml")
    verification_path = Path("artifacts/cities/verification-v3.json")
    if verification_path.exists():
        verified = evidence(str(verification_path).replace("\\", "/"))
        for name, report in verified["reports"].items():
            metric_lines.append(
                f"| Local verification / {name} | {report['passed']} passed; {report['failures'] + report['errors']} failures/errors; {report['skipped']} intentionally inapplicable cases | {link('artifacts/cities/verification-v3.json')}; actual local machine reports, not hosted CI or production status. |"
            )
    elif junit.exists():
        root = ET.parse(junit).getroot()
        suites = list(root.iter("testsuite"))
        tests = sum(int(s.get("tests", 0)) for s in suites)
        failures = sum(int(s.get("failures", 0)) + int(s.get("errors", 0)) for s in suites)
        skipped = sum(int(s.get("skipped", 0)) for s in suites)
        metric_lines.append(
            f"| Local Python verification | {tests - skipped - failures} passed; {failures} failures/errors; {skipped} skips | Derived from local JUnit output; generated test counts do not establish browser/deployment status. |"
        )
    metric_lines += [
        "",
        "## Unmeasured or not established",
        "",
        "No verified city-image mAP/IDF1, lane mapping accuracy, visual queue MAE, independent calibrated city twin, current detector-to-camera fusion, field traffic savings, bus/pedestrian delay improvements, controller speedup, city-wide feed uptime, human usability results, or newly deployed production version. The GNN is evaluated on highway speeds only. RL, self-supervised transfer and surrogate speedups are not established by the listed experiments.",
        "",
        "The old outage diagnostic did not remove sensor input from max-pressure. It is excluded from superiority claims; the operational v3 harness fixes shared outage visibility. Nominal v2 cohorts remain frozen.",
        "",
        "## Exact evidence hashes",
        "",
        "| Source | SHA-256 |",
        "|---|---|",
    ]
    metric_lines += [f"| {link(p)} | `{digest}` |" for p, digest in sorted(sources.items())]
    transfer = next(s for s in study["suites"] if s["suite"] == "transfer.json")
    ingol = next(
        p
        for p in transfer["paired"]
        if p["city"] == "ingolstadt1" and p["baseline"] == "original_mpc"
    )
    bullets = [
        "# Evidence-backed resume bullet candidates",
        "",
        "Generated from actual artifacts. Choose claims appropriate to the role; include the qualifications when discussing the work. Projections and unmeasured targets are excluded.",
        "",
        "## Software engineering",
        "",
        f"- Built a five-city official traffic ingestion and simulation platform, discovering {catalogs:,} camera records and processing {len(observations)} verified snapshot observations across {len(cameras)} sampled cameras.",
        f"  - Evidence: source-health + toronto-intelligence; HTTPS allowlists, bounded reads/retries, privacy-preserving aggregate retention. Catalog count is metadata scale; only sampled image access was verified. Hardware: {hardware}; source checks are one-time observations, not uptime measurements.",
        "",
        "## Machine learning engineering",
        "",
    ]
    if new:
        h = next(h for h in new["results"] if h["horizon_minutes"] == 5)
        m = next(m for m in h["models"] if m["selected_on_validation"])
        reduction = 100 * (1 - m["metrics"]["mae"] / old["atlas_gradient_boosting"]["mae"])
        if reduction > 0:
            bullets += [
                f"- Developed validation-selected {m['model'].replace('_', ' ')} traffic forecasting, reducing five-minute METR-LA MAE by {reduction:.2f}% over the original ATLAS ML baseline ({m['metrics']['mae']:.3f} vs {old['atlas_gradient_boosting']['mae']:.3f} mph) across 207 sensors.",
                f"  - Experiment: {new['experiment_id']}; chronological 70/10/20, {m['metrics']['valid_targets']:,} valid targets, same original test period. CPU: {hardware}, four threads; all-sensor p95 {m['all_207_sensor_latency_ms_p95']:.2f} ms. Static graph-assisted classical model, not a neural GNN; independent external replication outstanding.",
            ]
    else:
        bullets += [
            f"- Evaluated traffic forecasting across 207 METR-LA sensors, achieving {old['atlas_gradient_boosting']['mae']:.3f} mph five-minute MAE against {old['persistence']['mae']:.3f} mph persistence.",
            f"  - Experiment: real_forecasting; historical CPU run on {hardware}; temporal holdout, not cross-city camera forecasting.",
        ]
    neural_five = next(
        p
        for p in neural["paired_analysis"]
        if p["horizon_minutes"] == 5 and p["baseline"] == "original_atlas_ml"
    )
    neural_ci = neural_five["paired_day_block_ci95_pct"]
    neural_model = next(
        m
        for h in neural["results"]
        if h["horizon_minutes"] == 5
        for m in h["models"]
        if m["model"] == h["selected_on_validation"]
    )
    bullets += [
        f"- Implemented a {neural_model['parameters']:,}-parameter directional graph neural traffic forecaster, reducing five-minute METR-LA MAE by {neural_five['reduction_pct']:.2f}% over the original ML baseline ({neural_five['new_mae_mph']:.3f} vs {neural_five['baseline_mae_mph']:.3f} mph) across 207 sensors.",
        f"  - Experiment: {neural['experiment_id']}; {neural_five['valid_targets']:,} valid held-out targets, best epoch selected on validation; paired day-block 95% interval [{neural_ci[0]:.2f}, {neural_ci[1]:.2f}]%. Four CPU threads; forward-only p95 {neural_model['all_207_sensor_forward_ms_p95']:.3f} ms. Highway domain, one training seed, shared historical test period; external replication and calibrated intervals remain pending.",
    ]
    bullets += [
        "",
        "## Computer vision engineering",
        "",
        f"- Built a CPU traffic video pipeline achieving {detection['metrics']['map50']:.3f} mAP@50 and {tracking['metrics']['IDF1']:.3f} IDF1 across {pipeline['metrics']['frames']:,} annotated UA-DETRAC frames.",
        f"  - Experiments: real_detection, real_tracking, real_video_pipeline; three official test sequences; {hardware}, {pipeline['metrics']['pipeline_fps']:.1f} complete-pipeline FPS. Vehicle aggregate class; calibrated road speeds and visual queues not validated.",
        "",
        "## Applied AI / research engineering",
        "",
        f"- Validated traffic controllers in {total_runs} paired SUMO runs across seven modeled networks, improving Ingolstadt mean delay by {ingol['mean_paired_reduction_pct']:.2f}% versus the frozen ATLAS MPC over {ingol['pairs']} seeds.",
        "  - Experiments: five-city-nominal + transfer, predeclared seeds 20001–20020 / 34001–34020; Linux SUMO 1.27.1. Ingolstadt improvement primarily uses a topology-triggered max-pressure fallback; no superiority over max-pressure. Cologne and five city corridors regressed versus the frozen MPC. Not field validation.",
        "",
        "## Systems and performance engineering",
        "",
        f"- Engineered an end-to-end CPU traffic pipeline processing {pipeline['metrics']['frames']:,} real annotated frames at {pipeline['metrics']['pipeline_fps']:.1f} FPS, including tracking, analytics and SQLite/JSON persistence.",
        f"  - Experiment: real_video_pipeline; {hardware}, peak RSS {pipeline['metrics']['memory_peak_rss_mb']:.1f} MiB. Lossless video preparation excluded; developer machine, no isolated host. New controller profile does not support a speedup claim.",
        "",
        "Full numerical evidence, hardware, comparator context, limitations and source hashes: [VERIFIED_ENGINEERING_METRICS.md](VERIFIED_ENGINEERING_METRICS.md).",
    ]
    return "\n".join(metric_lines) + "\n", "\n".join(bullets) + "\n"


if __name__ == "__main__":
    metrics, bullets = generate()
    Path("docs/VERIFIED_ENGINEERING_METRICS.md").write_text(metrics, encoding="utf-8")
    Path("docs/RESUME_BULLETS.md").write_text(bullets, encoding="utf-8")
    print("Generated evidence-backed metrics and five role-specific resume sections")
